Output static/demo.gif
Set Shell zsh

Set FontSize 16
Set Width 1200
Set Height 600

Type "cargo run -- --help"
Sleep 500ms
Enter
Sleep 4s
Type "cargo run -- --openapi-path examples/petstore.json"
Sleep 2s
Enter
Sleep 1s
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 500ms
Down
Sleep 1s
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 500ms
Right
Sleep 4s
Type "q"
Sleep 500ms
Ctrl+D

