Output static/demo.gif
Set Shell zsh

Set FontSize 16
Set Width 1200
Set Height 800

Set Padding 20
Set FontFamily "JetBrains Mono"

Set WindowBar Colorful

Set Theme "Catppuccin Mocha"
Sleep 2s
Type "cargo run -q -- --openapi-path examples/petstore.json"
Sleep 2s
Enter
Sleep 3s
Enter
Down@2s 9
Enter
Sleep 2s
Down@1s 3
Enter
Sleep 1s
Right@1s
Down@2s
Enter
Sleep 1s
Left@1s
Down@2s
Enter
Right@2s 3
Down@2s 10
Right@1s 2
Sleep 10s
Type "q"
Sleep 1s
Ctrl+D

