Output static/filter.gif
Hide
    Set Shell zsh

    Set FontSize 16
    Set Width 1200
    Set Height 600

    Set Padding 20
    Set FontFamily "JetBrains Mono"

    Set WindowBar Colorful
    Set WindowBarSize 40

    Set Theme "Catppuccin Mocha"
    Type "cargo run -- --openapi-path examples/stripe/spec.yml"
    Enter
    Sleep 10s
    Set TypingSpeed 400ms
Show
Sleep 2s
Type "/"
Sleep 2s
Type "balance"
Enter
Sleep 2s
Type "j"
Type "j"

Sleep 5s
Hide
    Type "q"
    Ctrl+D
Show
