// OpenAPI v3.1.0 Specification
//
// OpenAPI inside OpenAPI
//
// The version of the OpenAPI document: 3.1.0
//
// Generated by: https://openapi-generator.tech

use crate::v31;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ExternalDocumentation {
  #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
  pub description: Option<String>,
  #[serde(rename = "url")]
  pub url: String,
}

impl ExternalDocumentation {
  pub fn new(url: String) -> ExternalDocumentation {
    ExternalDocumentation { description: None, url }
  }
}
