// OpenAPI v3.1.0 Specification
//
// OpenAPI inside OpenAPI
//
// The version of the OpenAPI document: 3.1.0
//
// Generated by: https://openapi-generator.tech

use crate::v31;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Info {
  #[serde(rename = "title")]
  pub title: String,
  #[serde(rename = "summary", skip_serializing_if = "Option::is_none")]
  pub summary: Option<String>,
  #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
  pub description: Option<String>,
  #[serde(rename = "termsOfService", skip_serializing_if = "Option::is_none")]
  pub terms_of_service: Option<String>,
  #[serde(rename = "contact", skip_serializing_if = "Option::is_none")]
  pub contact: Option<Box<v31::Contact>>,
  #[serde(rename = "license", skip_serializing_if = "Option::is_none")]
  pub license: Option<Box<v31::License>>,
  #[serde(rename = "version")]
  pub version: String,
}

impl Info {
  pub fn new(title: String, version: String) -> Info {
    Info { title, summary: None, description: None, terms_of_service: None, contact: None, license: None, version }
  }
}
