// OpenAPI v3.1.0 Specification
//
// OpenAPI inside OpenAPI
//
// The version of the OpenAPI document: 3.1.0
//
// Generated by: https://openapi-generator.tech

use crate::v31;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct MediaType {
  #[serde(rename = "schema", default, skip_serializing_if = "Option::is_none")]
  pub schema: Option<serde_json::Value>,
  #[serde(rename = "encoding", skip_serializing_if = "Option::is_none")]
  pub encoding: Option<std::collections::BTreeMap<String, v31::Encoding>>,
  #[serde(rename = "example", default, skip_serializing_if = "Option::is_none")]
  pub example: Option<serde_json::Value>,
  #[serde(rename = "examples", skip_serializing_if = "Option::is_none")]
  pub examples: Option<std::collections::BTreeMap<String, serde_json::Value>>,
}

impl MediaType {
  pub fn new() -> MediaType {
    MediaType { schema: None, encoding: None, example: None, examples: None }
  }
}
