// OpenAPI v3.1.0 Specification
//
// OpenAPI inside OpenAPI
//
// The version of the OpenAPI document: 3.1.0
//
// Generated by: https://openapi-generator.tech

use crate::v31;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OauthFlows {
  #[serde(rename = "implicit", skip_serializing_if = "Option::is_none")]
  pub implicit: Option<Box<v31::Implicit>>,
  #[serde(rename = "password", skip_serializing_if = "Option::is_none")]
  pub password: Option<Box<v31::Password>>,
  #[serde(rename = "clientCredentials", skip_serializing_if = "Option::is_none")]
  pub client_credentials: Option<Box<v31::ClientCredentials>>,
  #[serde(rename = "authorizationCode", skip_serializing_if = "Option::is_none")]
  pub authorization_code: Option<Box<v31::AuthorizationCode>>,
}

impl OauthFlows {
  pub fn new() -> OauthFlows {
    OauthFlows { implicit: None, password: None, client_credentials: None, authorization_code: None }
  }
}
