/*
 * OpenAPI v3.1.0 Specification
 *
 * OpenAPI inside OpenAPI
 *
 * The version of the OpenAPI document: 3.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Openapi {
    #[serde(rename = "openapi", deserialize_with = "Option::deserialize")]
    pub openapi: Option<serde_json::Value>,
    #[serde(rename = "info")]
    pub info: Box<models::Info>,
    #[serde(rename = "jsonSchemaDialect", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub json_schema_dialect: Option<Option<serde_json::Value>>,
    #[serde(rename = "servers", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub servers: Option<Option<serde_json::Value>>,
    #[serde(rename = "paths", skip_serializing_if = "Option::is_none")]
    pub paths: Option<serde_json::Value>,
    #[serde(rename = "webhooks", skip_serializing_if = "Option::is_none")]
    pub webhooks: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "components", skip_serializing_if = "Option::is_none")]
    pub components: Option<Box<models::Components>>,
    #[serde(rename = "security", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub security: Option<Option<serde_json::Value>>,
    #[serde(rename = "tags", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Option<serde_json::Value>>,
    #[serde(rename = "externalDocs", skip_serializing_if = "Option::is_none")]
    pub external_docs: Option<Box<models::ExternalDocumentation>>,
}

impl Openapi {
    pub fn new(openapi: Option<serde_json::Value>, info: models::Info) -> Openapi {
        Openapi {
            openapi,
            info: Box::new(info),
            json_schema_dialect: None,
            servers: None,
            paths: None,
            webhooks: None,
            components: None,
            security: None,
            tags: None,
            external_docs: None,
        }
    }
}

