// OpenAPI v3.1.0 Specification
//
// OpenAPI inside OpenAPI
//
// The version of the OpenAPI document: 3.1.0
//
// Generated by: https://openapi-generator.tech

use crate::v31;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Password {
  #[serde(rename = "tokenUrl")]
  pub token_url: String,
  #[serde(rename = "refreshUrl", skip_serializing_if = "Option::is_none")]
  pub refresh_url: Option<String>,
  #[serde(rename = "scopes")]
  pub scopes: std::collections::HashMap<String, String>,
}

impl Password {
  pub fn new(token_url: String, scopes: std::collections::HashMap<String, String>) -> Password {
    Password { token_url, refresh_url: None, scopes }
  }
}
