// OpenAPI v3.1.0 Specification
//
// OpenAPI inside OpenAPI
//
// The version of the OpenAPI document: 3.1.0
//
// Generated by: https://openapi-generator.tech

use crate::v31;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RequestBody {
  #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
  pub description: Option<String>,
  #[serde(rename = "content")]
  pub content: std::collections::HashMap<String, v31::MediaType>,
  #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
  pub required: Option<bool>,
}

impl RequestBody {
  pub fn new(content: std::collections::HashMap<String, v31::MediaType>) -> RequestBody {
    RequestBody { description: None, content, required: None }
  }
}
