// OpenAPI v3.1.0 Specification
//
// OpenAPI inside OpenAPI
//
// The version of the OpenAPI document: 3.1.0
//
// Generated by: https://openapi-generator.tech

use crate::v31;

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Responses {
  #[serde(rename = "default", default, skip_serializing_if = "Option::is_none")]
  pub default: Option<serde_json::Value>,
}

impl Responses {
  pub fn new() -> Responses {
    Responses { default: None }
  }
}
